### ISSUE TITLE
License mismatch with readme.md?

### ISSUE THREAD

**Issue by bdamokos** [fatihak/InkyPi#1]
Great project, congratulations!

A quick question/note: in your readme.md you put the license as MIT, and in License.md you put it as GPL 3.0? Might make sense to choose one or the other, they are both open source licenses, allowing others to build on your project, which is great!

**Comment by fatihak** [comment]
Good catch, updated the README here: https://github.com/fatihak/InkyPi/commit/12c5d59cd6eeb4102d829b73074444203afb35af

Closing out the first Issue of the project!
